version: 2.1

# Define the jobs we want to run for this project
jobs:
    build:
        docker:
            - image: cimg/base:2021.04
              auth:
                  username: mydockerhub-user
                  password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
        steps:
            - checkout
            - run: echo "this is the build job"
            - run: npm install
            - run: npm build
    test:
        docker:
            - image: cimg/base:2021.04
              auth:
                  username: mydockerhub-user
                  password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
        steps:
            - checkout
            - run: echo "this is the test job"
            - run: npm test

# Orchestrate our job run sequence
workflows:
    build_and_test:
        jobs:
            - build
            - test
